### ISSUE TITLE
LSTM执行后不停止也没有反应

### ISSUE THREAD

**Issue by silkyrose** [ZhiqingXiao/pytorch-book#3]
迭代10000次之后，预测时，报错如下：
Traceback (most recent call last):
  File "E:/！paper/第四篇/实验/app/gdp.py", line 85, in <module>
    display(df_pred.loc[2001:])
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\display.py", line 274, in display
    print(*objs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py", line 750, in __repr__
    show_dimensions=show_dimensions,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py", line 882, in to_string
    return formatter.to_string(buf=buf, encoding=encoding)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\formats\format.py", line 921, in to_string
    return self.get_result(buf=buf, encoding=encoding)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\formats\format.py", line 520, in get_result
    self.write_result(buf=f)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\formats\format.py", line 844, in write_result
    max_len = Series(lines).str.len().max()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 11457, in stat_func
    func, name=name, axis=axis, skipna=skipna, numeric_only=numeric_only
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 4236, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\nanops.py", line 120, in f
    result = bn_func(values, axis=axis, **kwds)
TypeError: 'NoneType' object is not callable

**Comment by silkyrose** [comment]
下载世行的gdp数据之后，dat打印不出来（Nonetype），但是能处理dat，shape和index都是对的。
In [1]: from pandas_datareader import wb
In [3]: dat = wb.download(indicator='NY.GDP.PCAP.KD', country=['US', 'CA', 'MX'], start=2005, end=2008)

In [4]: print(dat)
dat应该能被打印出来，
数据格式：
    NY.GDP.PCAP.KD
country       year
Canada        2008  36005.5004978584
              2007  36182.9138439757
              2006  35785.9698172849
              2005  35087.8925933298
Mexico        2008  8113.10219480083
              2007  8119.21298908649
              2006  7961.96818458178
              2005  7666.69796097264
United States 2008  43069.5819857208
              2007  43635.5852068142
              2006   43228.111147107
              2005  42516.3934699993

**Comment by silkyrose** [comment]
df也打印不出来，也是nonetype，请问哪位知道原因？

**Comment by ZhiqingXiao** [comment]
I have updated the repo so that the data are attached as a CSV file.
